<a href="https://colab.research.google.com/github/nithinkumar888/PDS_B14_10B4/blob/main/Lab%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
marks = np.array([
    [78, 85, 92],   # Student 1
    [88, 76, 95],   # Student 2
    [90, 82, 87],   # Student 3
    [69, 72, 80],   # Student 4
    [95, 89, 99]    # Student 5
])

print("Student Marks Array:\n", marks)
avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)

print("\nOverall Average Marks:", avg_marks)
print("Minimum Marks:", min_marks)
print("Maximum Marks:", max_marks)
print("\nMarks of Student 2:", marks[1, :])  # Row 2
print("Marks of Student 4:", marks[3, :])  # Row 4
above_80 = marks > 80
print("\nBoolean Array (True if score > 80):\n", above_80)

students_above_80 = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 in at least one subject:\n", marks[students_above_80])
subject_wise = marks.T
print("\nSubject-wise Marks (Each row = Subject, Columns = Students):\n", subject_wise)
print("\nAnalysis:")
print("- Student 5 performed exceptionally well with highest scores (close to 100).")
print("- Student 4 has relatively lower performance compared to others.")
print("- Subject 3 seems to have higher overall scores than Subject 1 and 2.")
print("- Most students scored above 80 at least once, showing good overall performance.")


Student Marks Array:
 [[78 85 92]
 [88 76 95]
 [90 82 87]
 [69 72 80]
 [95 89 99]]

Overall Average Marks: 85.13333333333334
Minimum Marks: 69
Maximum Marks: 99

Marks of Student 2: [88 76 95]
Marks of Student 4: [69 72 80]

Boolean Array (True if score > 80):
 [[False  True  True]
 [ True False  True]
 [ True  True  True]
 [False False False]
 [ True  True  True]]

Students scoring above 80 in at least one subject:
 [[78 85 92]
 [88 76 95]
 [90 82 87]
 [95 89 99]]

Subject-wise Marks (Each row = Subject, Columns = Students):
 [[78 88 90 69 95]
 [85 76 82 72 89]
 [92 95 87 80 99]]

Analysis:
- Student 5 performed exceptionally well with highest scores (close to 100).
- Student 4 has relatively lower performance compared to others.
- Subject 3 seems to have higher overall scores than Subject 1 and 2.
- Most students scored above 80 at least once, showing good overall performance.
